#!/bin/sh
#####################
# Name: st-video.sh
# Date: 2016-12-22
# Lisc: ISC
# Main: jadedctrl
# Desc: Does a thing with
#       a video-thingy thing
#       dsfgbvesrht fd
#####################

if [ -e "$HOME/.config/shelltube" ]
then
    . "$HOME/.config/shelltube"
fi

if test -z "$player_cmd"
then
    if command -v vlc > /dev/null
    then
        vlc --play-and-exit "${1}"
    elif command -v mplayer > /dev/null
    then
        mplayer --quiet "${1}"
    fi
else
    $player_cmd "${1}"
fi
