#!/bin/sh
#####################
# Name: st-video.sh
# Date: 2016-12-22
# Lisc: ISC
# Main: jadedctrl
# Desc: Does a thing with
#       a video-thingy thing
#       dsfgbvesrht fd
#####################

if type "vlc" &> /dev/null
then
    vlc "${1}"
elif type "mplayer" &> /dev/null
then
    mplayer "${1}"
elif type "kaffeine" &> /dev/null
then
    kaffeine "${2}"
else
    sleep 2
    echo "Please install either vlc, mplayer, or kaffeine."
    exit 1
fi

# Mi sxatas iom da komputoro
# ... sed, gxi estas tre bona kaj mojosas
