#!/bin/sh
#####################
# Name: st-video.sh
# Date: 2016-12-22
# Lisc: ISC
# Main: jadedctrl
# Desc: Does a thing with
#       a video-thingy thing
#       dsfgbvesrht fd
#####################

if [ -e $HOME/.config/shelltube ]
then
    . $HOME/.config/shelltube
fi

if test -z $player_cmd
then
    if type "vlc" &> /dev/null
    then
        vlc "${1}"
    elif type "mplayer" &> /dev/null
    then
        mplayer "${1}"
    fi
else
    $player_cmd "${1}"
fi
